development:
  adapter: postgresql
  encoding: unicode
  database: programmers_day_development
  pool: 5
  username: postgres
  password:

staging:
  adapter: postgresql
  encoding: unicode
  database: programmers_day_staging
  pool: 1
  timeout: 5000
  username: postgres
  password:

test: &test
  adapter: postgresql
  encoding: unicode
  database: programmers_day_test
  pool: 5
  username: postgres
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: programmers_day_production
  pool: 1
  timeout: 5000
  username: postgres
  password:
